# Cloud Builder pipeline
# https://cloud.google.com/container-builder/docs/overview

steps:
- name: 'gcr.io/cloud-builders/java/mvn:3.3.9-jdk-8'
  args:
  - 'clean'
  - 'install'
  - '--batch-mode'
  - '-Ddocker.image.name=${_IMAGE}'
  # only build the specified module
  - '--projects=${_MODULE}'
  - '--also-make'
  id: 'MVN_PACKAGE'

images: ['${_IMAGE}']
